### Get storage value
GET http://localhost:3000/contracts/24/call/get

### Set storage value
POST http://localhost:3000/contracts/20/call
content-type: application/json

{
    "func": "set",
    "args": []
}

### Pay
POST http://localhost:3000/contracts/20/call
content-type: application/json

{
    "func": "pay",
    "quant": 1,
    "args": []
}

### Deploy SC
POST http://localhost:3000/contracts
content-type: application/json

{
    "abi": "[{\"constant\":false,\"inputs\":[],\"name\":\"pay\",\"outputs\":[],\"payable\":true,\"stateMutability\":\"payable\",\"type\":\"function\"},{\"constant\":false,\"inputs\":[],\"name\":\"set\",\"outputs\":[],\"payable\":false,\"stateMutability\":\"nonpayable\",\"type\":\"function\"},{\"constant\":true,\"inputs\":[],\"name\":\"get\",\"outputs\":[{\"internalType\":\"uint256\",\"name\":\"\",\"type\":\"uint256\"}],\"payable\":false,\"stateMutability\":\"view\",\"type\":\"function\"}]",
    "bytecode": "608060405234801561001057600080fd5b5060c48061001f6000396000f3fe60806040526004361060305760003560e01c80631b9265b81460355780636d4ce63c14603d578063b8e010de146065575b600080fd5b603b6079565b005b348015604857600080fd5b50604f607b565b6040518082815260200191505060405180910390f35b348015607057600080fd5b5060776084565b005b565b60008054905090565b61014d60008190555056fea265627a7a7231582089acc518313bcf748f33cb29e749c54cd82c0daeb36aa5676bb99df692df840764736f6c63430005110032",
    "source": "pragma solidity^0.5.0;contract SimpleStorage{uint x;function set()public{x=333}function get()public view returns(uint){return x}function pay()public payable{}}"
}

### Get all stored SCs
GET http://localhost:3000/contracts

### Get one SC
GET http://localhost:3000/contracts/4

### Update SC
PUT http://localhost:3000/contracts
content-type: application/json

{
    "tx": "0xb6edf1f70446d488740b578221df8cd58128fc798941f78a16c67cb715849245",
    "abi": "[{\"constant\":false,\"inputs\":[],\"name\":\"get\",\"outputs\":[{\"name\":\"\",\"type\":\"uint256\"}],\"payable\":false,\"type\":\"function\",\"stateMutability\":\"nonpayable\"},{\"constant\":false,\"inputs\":[],\"name\":\"set\",\"outputs\":[],\"payable\":false,\"type\":\"function\",\"stateMutability\":\"nonpayable\"}]",
    "source": "pragma solidity^0.4.8;contract SimpleStorage{uint x;function set(){x=333}function get()returns(uint){return x}}"
}

### Send ETH
POST http://localhost:3000/transactions
content-type: application/json

{
    "new": {
        "to": "0x54c379a6db831e890c9236b6339B505807Dc705C",
        "quant": 0.01
    }
}

### Update tx
PUT http://localhost:3000/transactions
Content-type: application/json

{
    "hash": "0x5114267435cbf4ca29b8dd32882075924c49e8cdaa876f6c21c2540b28a49319"
}

### Get all tx
GET http://localhost:3000/transactions

### Get one tx
GET http://localhost:3000/transactions/0x749c11ff92075083bad4ba14a7e93745496fae9711a88f72fa1599d379f0b918

### Get balance
GET http://localhost:3000/transactions/balance/0xe64e40EF4def381F28eC7a08296DD7df521f8ea8

### Sign tx
POST http://localhost:3000/transactions/sign
content-type: application/json

{
    "to": "0x54c379a6db831e890c9236b6339B505807Dc705C",
    "quant": 0.01
}

### Send raw tx
POST http://localhost:3000/transactions
content-type: application/json

{
    "raw": {
        "tx": "0x02f87382053921843b9aca00843b9aca0e8252089454c379a6db831e890c9236b6339b505807dc705c872386f26fc1000080c001a01c3e5831eb374d8a7c4a20e35e729912883754ae429189e5b32968de93650ad0a04b0253173a9a30bf1e619a3c6b2216f7f430c2af77c655bb8353178bf9a65bba"
    }
}