### Get storage value
GET http://localhost:3000/contracts/3/call/get

### Set storage value
POST http://localhost:3000/contracts/3/call
content-type: application/json

{
    "func": "set"
}

### Pay
POST http://localhost:3000/contracts/3/call
content-type: application/json

{
    "func": "pay",
    "quant": 1
}

### Deploy SC
POST http://localhost:3000/contracts
content-type: application/json

{
    "abi": "[{\"constant\":false,\"inputs\":[],\"name\":\"pay\",\"outputs\":[],\"payable\":true,\"stateMutability\":\"payable\",\"type\":\"function\"},{\"constant\":false,\"inputs\":[],\"name\":\"set\",\"outputs\":[],\"payable\":false,\"stateMutability\":\"nonpayable\",\"type\":\"function\"},{\"constant\":true,\"inputs\":[],\"name\":\"get\",\"outputs\":[{\"internalType\":\"uint256\",\"name\":\"\",\"type\":\"uint256\"}],\"payable\":false,\"stateMutability\":\"view\",\"type\":\"function\"}]",
    "bytecode": "608060405234801561001057600080fd5b5060c48061001f6000396000f3fe60806040526004361060305760003560e01c80631b9265b81460355780636d4ce63c14603d578063b8e010de146065575b600080fd5b603b6079565b005b348015604857600080fd5b50604f607b565b6040518082815260200191505060405180910390f35b348015607057600080fd5b5060776084565b005b565b60008054905090565b61014d60008190555056fea265627a7a72315820a59b715eb5b0778305021a2de3f2c5529462c2827e1cb9ec510d498b1b7de71f64736f6c634300050e0032",
    "source": "pragma solidity ^0.5.0; contract SimpleStorage { uint x; function set() public { x = 333; } function get() public view returns (uint) { return x; } function pay() public payable {} }"
}

### Get all stored SCs
GET http://localhost:3000/contracts?pageSize=3&pageIndex=2

### Get one SC
GET http://localhost:3000/contracts/1

### Update & Verify SC
PATCH http://localhost:3000/contracts
content-type: application/json

{
    "tx": "0x0ce48a5a0779e86dcdfd546098de79e2ba4e46bca478461f6c6f9a9565c55d93",
    "abi": "[{\"constant\":false,\"inputs\":[],\"name\":\"get\",\"outputs\":[{\"name\":\"\",\"type\":\"uint256\"}],\"payable\":false,\"type\":\"function\",\"stateMutability\":\"nonpayable\"},{\"constant\":false,\"inputs\":[],\"name\":\"set\",\"outputs\":[],\"payable\":false,\"type\":\"function\",\"stateMutability\":\"nonpayable\"}]",
    "source": "pragma solidity ^0.5.0; contract SimpleStorage { uint x; function set() public { x = 333; } function get() public view returns (uint) { return x; } function pay() public payable {} }",
    "fileName": "contract-2c390734c4.sol",
    "compilerVersion": "0.5.14"
}

### Send ETH
POST http://localhost:3000/transactions
content-type: application/json

{
    "new": {
        "to": "0x1b973BC2cb3e4413a6B3E302357Fe9d1D586028e",
        "quant": 4.3,
        "gasSettings": {
            "gasLimit": 21000,
            "gasPrice": 1122646121
        }
    }
}

### Update tx
PATCH  http://localhost:3000/transactions
Content-type: application/json

{
    "txHash": "0xa83dc996c182595ee819868a83e0f5b39c3088f04051494dba9fa784f4430a01"
}

### Get all tx
GET http://localhost:3000/transactions?pageSize=5&pageIndex=2

### Get one tx
GET http://localhost:3000/transactions/0x9df7ba8ae253f458defb309e55c6f374c31c504f1e19f073a913ec8a87fa717d

### Get balance
GET http://localhost:3000/transactions/balance/0xA46B8f9D99446AF2E0d536B4A89C17Cb62A6ad8A

### Sign tx
POST http://localhost:3000/transactions/sign
content-type: application/json

{
    "to": "0x1b973BC2cb3e4413a6B3E302357Fe9d1D586028e",
    "quant": 4
}

### Send raw tx
POST http://localhost:3000/transactions
content-type: application/json

{
    "raw": {
        "tx": "0x02f87482053914843b9aca0084443bdd24825208941b973bc2cb3e4413a6b3e302357fe9d1d586028e883782dace9d90000080c001a02541d4e71162e152def63edb54e8c53a58cde7971af36f1382af8a7489060043a073e94bf43763a48c2e9bd4cb5597d378775c9f75d3d8f4b39ccf3aaaaeee17ab"
    }
}