### Get storage value
GET http://localhost:3000/contracts/26/call/get

### Set storage value
POST http://localhost:3000/contracts/26/call
content-type: application/json

{
    "func": "set",
    "args": []
}

### Pay
POST http://localhost:3000/contracts/26/call
content-type: application/json

{
    "func": "pay",
    "quant": 1,
    "args": []
}

### Deploy SC
POST http://localhost:3000/contracts
content-type: application/json

{
    "abi": "[{\"constant\":false,\"inputs\":[],\"name\":\"pay\",\"outputs\":[],\"payable\":true,\"stateMutability\":\"payable\",\"type\":\"function\"},{\"constant\":false,\"inputs\":[],\"name\":\"set\",\"outputs\":[],\"payable\":false,\"stateMutability\":\"nonpayable\",\"type\":\"function\"},{\"constant\":true,\"inputs\":[],\"name\":\"get\",\"outputs\":[{\"internalType\":\"uint256\",\"name\":\"\",\"type\":\"uint256\"}],\"payable\":false,\"stateMutability\":\"view\",\"type\":\"function\"}]",
    "bytecode": "608060405234801561001057600080fd5b5060c48061001f6000396000f3fe60806040526004361060305760003560e01c80631b9265b81460355780636d4ce63c14603d578063b8e010de146065575b600080fd5b603b6079565b005b348015604857600080fd5b50604f607b565b6040518082815260200191505060405180910390f35b348015607057600080fd5b5060776084565b005b565b60008054905090565b61014d60008190555056fea265627a7a72315820a59b715eb5b0778305021a2de3f2c5529462c2827e1cb9ec510d498b1b7de71f64736f6c634300050e0032",
    "source": "pragma solidity ^0.5.0; contract SimpleStorage { uint x; function set() public { x = 333; } function get() public view returns (uint) { return x; } function pay() public payable {} }",
    "fileName": "contract-2c390734c4.sol",
    "compilerVersion": "0.5.14"
}

### Get all stored SCs
GET http://localhost:3000/contracts

### Get one SC
GET http://localhost:3000/contracts/26

### Update SC
PUT http://localhost:3000/contracts
content-type: application/json

{
    "tx": "0x4b7432a6d6a053321091d8bffcf24ecd44cc5ed7bbd2574d01d91efa1040119e",
    "abi": "[{\"constant\":false,\"inputs\":[],\"name\":\"get\",\"outputs\":[{\"name\":\"\",\"type\":\"uint256\"}],\"payable\":false,\"type\":\"function\",\"stateMutability\":\"nonpayable\"},{\"constant\":false,\"inputs\":[],\"name\":\"set\",\"outputs\":[],\"payable\":false,\"type\":\"function\",\"stateMutability\":\"nonpayable\"}]",
    "source": "pragma solidity ^0.5.0; contract SimpleStorage { uint x; function set() public { x = 333; } function get() public view returns (uint) { return x; } function pay() public payable {} }",
    "fileName": "contract-2c390734c4.sol",
    "compilerVersion": "0.5.14"
}

### Send ETH
POST http://localhost:3000/transactions
content-type: application/json

{
    "new": {
        "to": "0x54c379a6db831e890c9236b6339B505807Dc705C",
        "quant": 0.01
    }
}

### Update tx
PUT http://localhost:3000/transactions
Content-type: application/json

{
    "hash": "0x5114267435cbf4ca29b8dd32882075924c49e8cdaa876f6c21c2540b28a49319"
}

### Get all tx
GET http://localhost:3000/transactions

### Get one tx
GET http://localhost:3000/transactions/0x831df208aeb870a71a48e1a9e7d7d5aff4b7e7c7ee625de48ca0063fe37f297c

### Get balance
GET http://localhost:3000/transactions/balance/0x831df208aeb870a71a48e1a9e7d7d5aff4b7e7c7ee625de48ca0063fe37f297c

### Sign tx
POST http://localhost:3000/transactions/sign
content-type: application/json

{
    "to": "0x54c379a6db831e890c9236b6339B505807Dc705C",
    "quant": 0.01
}

### Send raw tx
POST http://localhost:3000/transactions
content-type: application/json

{
    "raw": {
        "tx": "0x02f87382053927843b9aca00843b9aca0e82523089454c379a6db831e890c9236b6339b505807dc705c872386f26fc1000080c001a0a9798c6fa2d372a88608fd3d04f99e39ea14332f33069111fc318c9ea366bda6a029b732f9f04c77c4bdf85929fa0a8194940dfbdb41a861cf7f43f4a925ed6cb6"
    }
}